sudo: required
dist: trusty
language: node_js
before_install:
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb https://download.mono-project.com/repo/ubuntu stable-trusty main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install -y dotnet-sdk-2.1
  - sudo apt-get install -y mono-develop
script:
  - dotnet restore
  - cd src
  - dotnet fable yarn-run build
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
